apiVersion: v1
kind: Secret
metadata:
  name: longhorn-auth
  namespace: longhorn-system
type: Opaque
stringData:
  # Standaard: user=admin, password=admin
  # Wil je een ander wachtwoord? Genereer een string via een 'htpasswd generator'
  users: |
    admin:$apr1$r/B6.h22$aK4M7Fq.yq5L3jU5.Cg.0.