apiVersion: v1
kind: Secret
metadata:
  name: longhorn-auth
  namespace: longhorn-system
type: Opaque
stringData:
  # Standaard: user=admin, password=longhornadmin
  # AANBEVOLEN: Wil je een ander wachtwoord? Genereer een string via een 'htpasswd generator'
  users: |
    admin:$2a$13$YrWrB8AGLAB1RQyxNZqY6eHO8s4Vt9TS.roOs/CFZVuwxpK0zG.3y