apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
  namespace: portainer
  annotations:
    rgocd.argoproj.io/sync-wave: "1"
spec:
  insecureSkipVerify: true