---
# ==========================================
# FASE 1: K3s INSTALLATIE
# ==========================================

- name: 1. Installeer K3s Master
  hosts: server
  become: true
  tasks:
    - name: Download en installeer K3s (Master)
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wacht tot K3s start
      wait_for:
        port: 6443
        delay: 5
        timeout: 300

    - name: Haal node-token op (voor workers)
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token_base64

    - name: Stel token vast
      set_fact:
        k3s_token: "{{ k3s_token_base64['content'] | b64decode | trim }}"

- name: 2. Installeer K3s Workers
  hosts: agent
  become: true
  tasks:
    - name: Join het cluster
      shell: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars[groups['server'][0]]['inventory_hostname'] }}:6443 K3S_TOKEN={{ hostvars[groups['server'][0]]['k3s_token'] }} sh -"
      args:
        creates: /usr/local/bin/k3s-agent

# ==========================================
# FASE 2: CONFIGURATIE LOCALHOST (ANSIBLE VM)
# ==========================================

- name: 3. Configureer Ansible VM en haal Config op
  hosts: server
  become: true
  tasks:
    # Dit haalt het bestand van de SERVER naar je ANSIBLE VM
    - name: Haal kubeconfig op naar Ansible VM
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/config
        flat: yes

- name: 4. Configureer lokaal kubectl (Ansible VM)
  hosts: localhost
  connection: local
  gather_facts: false # Even uit voor snelheid, we zetten het later aan voor Argo
  tasks:
    # --- STAP 1: Installeer kubectl ---
    - name: Download en installeer kubectl binary
      become: true
      get_url:
        url: "https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    # --- STAP 2: Map voorbereiden ---
    - name: Maak .kube map aan in home directory
      file:
        path: ~/.kube
        state: directory
        mode: '0700'
    
    # --- STAP 3: Rechten goedzetten ---
    - name: Pas rechten aan van config
      file:
        path: ~/.kube/config
        mode: '0600'

    # --- STAP 4: De Fix (IP adres aanpassen) ---
    - name: Wijzig 127.0.0.1 naar het echte Master IP
      replace:
        path: ~/.kube/config
        regexp: 'https://127.0.0.1:6443'
        replace: "https://{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}:6443"

# ==========================================
# FASE 3: ARGOCD & APPS UITROLLEN
# ==========================================

- name: 5. Installeer ArgoCD en Bootstrap Cluster
  hosts: localhost
  connection: local
  gather_facts: true # NODIG voor ansible_env.HOME
  tasks:
    # --- DEEL 1: ArgoCD Installatie ---
    - name: Maak ArgoCD namespace aan
      kubernetes.core.k8s:
        name: argocd
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: "{{ ansible_env.HOME }}/.kube/config"

    - name: Download en installeer ArgoCD (Core installatie)
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/argoproj/argo-cd/v3.2.1/manifests/install.yaml
        namespace: argocd
        kubeconfig: "{{ ansible_env.HOME }}/.kube/config"

    - name: Wacht tot ArgoCD pods starten 
      shell: kubectl wait --for=condition=Available deployment/argocd-server -n argocd --timeout=300s
      environment:
        KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"

    - name: Patch ArgoCD service naar LoadBalancer 
      shell: |
        kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
      environment:
        KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"

    # --- DEEL 2: De Longhorn Fix ---
    
    - name: "[FIX] Maak Longhorn namespace aan (nodig voor SA)"
      kubernetes.core.k8s:
        name: longhorn-system
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: "{{ ansible_env.HOME }}/.kube/config"

    - name: "[FIX] Maak Longhorn ServiceAccount aan"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ ansible_env.HOME }}/.kube/config"
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: longhorn-service-account
            namespace: longhorn-system

    - name: "[FIX] Maak Longhorn ClusterRoleBinding aan"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ ansible_env.HOME }}/.kube/config"
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: longhorn-service-account-fix
          subjects:
          - kind: ServiceAccount
            name: longhorn-service-account
            namespace: longhorn-system
          roleRef:
            kind: ClusterRole
            name: cluster-admin
            apiGroup: rbac.authorization.k8s.io

    # --- DEEL 3: De Bootstrap Stap ---
    
    - name: Apply Root App (Bootstrap het cluster)
      command: kubectl apply -f https://raw.githubusercontent.com/Joe-designe/S3-eigenproject/main/Cluster/root-app.yaml
      environment:
        KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"

    # --- DEEL 4: Wachtwoord tonen ---

    - name: Haal ArgoCD admin wachtwoord op
      shell: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
      environment:
        KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"
      register: argocd_password

    - name: Toon inloggegevens
      debug:
        msg: 
          - "=============================================="
          - "AUTOMATISERING VOLTOOID!"
          - "----------------------------------------------"
          - "ArgoCD Gebruikersnaam: admin"
          - "ArgoCD Wachtwoord:     {{ argocd_password.stdout }}"
          - "----------------------------------------------"
          - "Dashboard URL's (via Ingress):"
          - "  - https://portainer.<MASTER-IP>.nip.io"
          - "  - https://longhorn.<MASTER-IP>.nip.io"
          - "  - https://grafana.<MASTER-IP>.nip.io"
          - "=============================================="